version: "3.5"

services:
  database:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - web

  elixir:
    build: ./docker/
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
      - "4001:4001"
    networks:
      - web
    command:
      - ./start.sh
  metabase:
    container_name: metabase
    image: metabase/metabase
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_NAME: "metabase"
      MB_DB_PORT: "5432"
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: "database"
    networks:
      - web
    ports:
      - "3000:3000"


networks:
  web:
    driver: bridge

volumes:
  postgres:
