name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the docker environment
      env:
        POSTGRES_DATABASE: database
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: docker-compose up -d
      
    - name: Install dependencies
      run: docker exec plutus_elixir_1 mix deps.get

    - name: Run tests
      run: docker exec plutus_elixir_1 mix test
