name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the docker environment
      env:
        POSTGRES_DATABASE: database
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: docker-compose up -d
      
    - name: Run tests
      run: docker exec plutus_elixir_1 mix test
      
    - name: Remove deps folder
      run: sudo rm -Rf deps _build cover assets
      
    - name: Generate deployment package
      run: zip -r deploy.zip .
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Plutus
        environment_name: Plutus-env
        version_label: 2
        region: us-east-2
        deployment_package: deploy.zip
